// api/_lib/templates.js
// CV template definitions shared by the DOCX and PDF generators.
//
// Every template is deliberately ATS-safe: single column, real selectable
// text, no tables/images/text boxes. Templates only vary typography, color
// accents, alignment, heading treatment, and spacing - the layout profile
// parsers handle best stays identical.

const TEMPLATES = {
  classic: {
    id: "classic",
    label: "Classic",
    description: "Centered headings, timeless and neutral",
    docxFont: "Calibri",
    pdfFont: "helvetica",
    accent: null, // black headings
    headingAlign: "center",
    headingRule: false,
    nameAlign: "center",
    docxBody: 23, // half-points (11.5pt)
    docxName: 26,
    pdfBody: 11,
    pdfName: 18,
  },
  modern: {
    id: "modern",
    label: "Modern",
    description: "Left-aligned with a blue accent and rules",
    docxFont: "Calibri",
    pdfFont: "helvetica",
    accent: "2B5CAB",
    headingAlign: "left",
    headingRule: true,
    nameAlign: "left",
    docxBody: 23,
    docxName: 28,
    pdfBody: 11,
    pdfName: 19,
  },
  elegant: {
    id: "elegant",
    label: "Elegant",
    description: "Serif type, centered, understated rules",
    docxFont: "Georgia",
    pdfFont: "times",
    accent: null,
    headingAlign: "center",
    headingRule: true,
    nameAlign: "center",
    docxBody: 22,
    docxName: 27,
    pdfBody: 10.5,
    pdfName: 18,
  },
  compact: {
    id: "compact",
    label: "Compact",
    description: "Tighter type to fit more on a page",
    docxFont: "Calibri",
    pdfFont: "helvetica",
    accent: null,
    headingAlign: "left",
    headingRule: false,
    nameAlign: "center",
    docxBody: 21, // 10.5pt
    docxName: 24,
    pdfBody: 10,
    pdfName: 16,
  },
  finance: {
    id: "finance",
    label: "Finance / Academic",
    description: "Serif, all-caps name, ruled headings — banking & quant classic",
    docxFont: "Georgia",
    pdfFont: "times",
    accent: null,
    headingAlign: "center",
    headingRule: true,
    nameAlign: "center",
    nameCaps: true,
    docxBody: 22,
    docxName: 26,
    pdfBody: 10.5,
    pdfName: 16,
  },
  scholar: {
    id: "scholar",
    label: "Scholar",
    description: "Serif with left ruled headings — graduate school style",
    docxFont: "Georgia",
    pdfFont: "times",
    accent: null,
    headingAlign: "left",
    headingRule: true,
    nameAlign: "center",
    docxBody: 22,
    docxName: 27,
    pdfBody: 10.5,
    pdfName: 17,
  },
  executive: {
    id: "executive",
    label: "Executive",
    description: "Large name, prominent role line, full-width rules",
    docxFont: "Calibri",
    pdfFont: "helvetica",
    accent: null,
    headingAlign: "center",
    headingRule: true,
    nameAlign: "center",
    docxBody: 22,
    docxName: 32,
    pdfBody: 10.5,
    pdfName: 21,
  },
  cardinal: {
    id: "cardinal",
    label: "Cardinal",
    description: "Centered name, navy left headings with rules",
    docxFont: "Calibri",
    pdfFont: "helvetica",
    accent: "1F3A93",
    headingAlign: "left",
    headingRule: true,
    nameAlign: "center",
    docxBody: 22,
    docxName: 27,
    pdfBody: 10.5,
    pdfName: 17,
  },
  onepage: {
    id: "onepage",
    label: "One-Page Tech",
    description: "Tight sans layout with ruled caps headings",
    docxFont: "Calibri",
    pdfFont: "helvetica",
    accent: null,
    headingAlign: "left",
    headingRule: true,
    nameAlign: "center",
    docxBody: 21,
    docxName: 25,
    pdfBody: 10,
    pdfName: 16,
  },
  timeline: {
    id: "timeline",
    label: "Timeline",
    description: "Blue name and rules, black headings — moderncv feel",
    docxFont: "Calibri",
    pdfFont: "helvetica",
    accent: "3873B3",
    headingUseAccent: false,
    headingAlign: "left",
    headingRule: true,
    nameAlign: "left",
    docxBody: 22,
    docxName: 28,
    pdfBody: 10.5,
    pdfName: 18,
  },
};

function getTemplate(id) {
  return TEMPLATES[id] || TEMPLATES.classic;
}

module.exports = { TEMPLATES, getTemplate };
